ALTER TABLE public.sef_alignments
  ADD COLUMN IF NOT EXISTS model_family TEXT NOT NULL DEFAULT 'pooled',
  ADD COLUMN IF NOT EXISTS coefficients JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS cv_metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS n_patients INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lineage TEXT;