import { readFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
import { loadSuppressionReport } from "@/lib/eeg/suppression-model.server";
import { promoteSuppressionFit } from "@/lib/eeg/suppression-promotion.server";
const session = JSON.parse(readFileSync(`${process.env["HOME"]}/.cache/lovable-auth/session.json`,"utf8")) as any;
const url = process.env["VITE_SUPABASE_URL"]!;
const admin = createClient(url, process.env["SUPABASE_SERVICE_ROLE_KEY"]!, { auth:{persistSession:false,autoRefreshToken:false}});
const userId = session.user_id as string;
const report = await loadSuppressionReport(admin as never, userId, 120000);
const outcome = await promoteSuppressionFit(admin as never, userId, report.fit, "full VitalDB refit");
console.log(JSON.stringify({ fit: { points: report.fit.points, cases: report.fit.cases, suppressed: report.fit.suppressedPoints, sensitivityGain: report.fit.sensitivityGain, maeGain: report.fit.maeGain, promotable: report.fit.promotable, blockedBy: report.fit.blockedBy }, outcome }, null, 2));
