/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedBedsideRouteImport } from './routes/_authenticated/bedside'
import { Route as AuthenticatedCasesRouteImport } from './routes/_authenticated/cases'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTermsRouteImport } from './routes/_authenticated/terms'
import { Route as AuthenticatedAdminBisBenchmarkRouteImport } from './routes/_authenticated/_admin/bis-benchmark'
import { Route as AuthenticatedAdminBlockersRouteImport } from './routes/_authenticated/_admin/blockers'
import { Route as AuthenticatedAdminBrainwavesRouteImport } from './routes/_authenticated/_admin/brainwaves'
import { Route as AuthenticatedAdminCalibrateRouteImport } from './routes/_authenticated/_admin/calibrate'
import { Route as AuthenticatedAdminCaptureRouteImport } from './routes/_authenticated/_admin/capture'
import { Route as AuthenticatedAdminCoebisRouteImport } from './routes/_authenticated/_admin/coebis'
import { Route as AuthenticatedAdminCompareRouteImport } from './routes/_authenticated/_admin/compare'
import { Route as AuthenticatedAdminCorpusUploadRouteImport } from './routes/_authenticated/_admin/corpus-upload'
import { Route as AuthenticatedAdminDepthRouteImport } from './routes/_authenticated/_admin/depth'
import { Route as AuthenticatedAdminDepthIntakeRouteImport } from './routes/_authenticated/_admin/depth-intake'
import { Route as AuthenticatedAdminDiscoveryRouteImport } from './routes/_authenticated/_admin/discovery'
import { Route as AuthenticatedAdminDrugsRouteImport } from './routes/_authenticated/_admin/drugs'
import { Route as AuthenticatedAdminExposureRouteImport } from './routes/_authenticated/_admin/exposure'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/_admin/feedback'
import { Route as AuthenticatedAdminFlagsRouteImport } from './routes/_authenticated/_admin/flags'
import { Route as AuthenticatedAdminKetamineRouteImport } from './routes/_authenticated/_admin/ketamine'
import { Route as AuthenticatedAdminModelsRouteImport } from './routes/_authenticated/_admin/models'
import { Route as AuthenticatedAdminOutcomesRouteImport } from './routes/_authenticated/_admin/outcomes'
import { Route as AuthenticatedAdminPairingRouteImport } from './routes/_authenticated/_admin/pairing'
import { Route as AuthenticatedAdminPathologyRouteImport } from './routes/_authenticated/_admin/pathology'
import { Route as AuthenticatedAdminPerformanceRouteImport } from './routes/_authenticated/_admin/performance'
import { Route as AuthenticatedAdminReferenceRouteImport } from './routes/_authenticated/_admin/reference'
import { Route as AuthenticatedAdminReplayRouteImport } from './routes/_authenticated/_admin/replay'
import { Route as AuthenticatedAdminSuppressionRouteImport } from './routes/_authenticated/_admin/suppression'
import { Route as AuthenticatedAdminTrainingRouteImport } from './routes/_authenticated/_admin/training'
import { Route as AuthenticatedAdminTrendsRouteImport } from './routes/_authenticated/_admin/trends'
import { Route as AuthenticatedAdminValidateRouteImport } from './routes/_authenticated/_admin/validate'
import { Route as AuthenticatedCaseCaseRefRouteImport } from './routes/_authenticated/case.$caseRef'
import { Route as AuthenticatedReportIdRouteImport } from './routes/_authenticated/report.$id'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAdminAdminPeopleRouteImport } from './routes/_authenticated/_admin/admin.people'
import { Route as ApiPublicHooksCoebisRefitRouteImport } from './routes/api/public/hooks/coebis-refit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBedsideRoute = AuthenticatedBedsideRouteImport.update({
  id: '/bedside',
  path: '/bedside',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesRoute = AuthenticatedCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTermsRoute = AuthenticatedTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBisBenchmarkRoute =
  AuthenticatedAdminBisBenchmarkRouteImport.update({
    id: '/bis-benchmark',
    path: '/bis-benchmark',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlockersRoute =
  AuthenticatedAdminBlockersRouteImport.update({
    id: '/blockers',
    path: '/blockers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBrainwavesRoute =
  AuthenticatedAdminBrainwavesRouteImport.update({
    id: '/brainwaves',
    path: '/brainwaves',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalibrateRoute =
  AuthenticatedAdminCalibrateRouteImport.update({
    id: '/calibrate',
    path: '/calibrate',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCaptureRoute =
  AuthenticatedAdminCaptureRouteImport.update({
    id: '/capture',
    path: '/capture',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoebisRoute =
  AuthenticatedAdminCoebisRouteImport.update({
    id: '/coebis',
    path: '/coebis',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCompareRoute =
  AuthenticatedAdminCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCorpusUploadRoute =
  AuthenticatedAdminCorpusUploadRouteImport.update({
    id: '/corpus-upload',
    path: '/corpus-upload',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDepthRoute = AuthenticatedAdminDepthRouteImport.update({
  id: '/depth',
  path: '/depth',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDepthIntakeRoute =
  AuthenticatedAdminDepthIntakeRouteImport.update({
    id: '/depth-intake',
    path: '/depth-intake',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDiscoveryRoute =
  AuthenticatedAdminDiscoveryRouteImport.update({
    id: '/discovery',
    path: '/discovery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDrugsRoute = AuthenticatedAdminDrugsRouteImport.update({
  id: '/drugs',
  path: '/drugs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminExposureRoute =
  AuthenticatedAdminExposureRouteImport.update({
    id: '/exposure',
    path: '/exposure',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFlagsRoute = AuthenticatedAdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKetamineRoute =
  AuthenticatedAdminKetamineRouteImport.update({
    id: '/ketamine',
    path: '/ketamine',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModelsRoute =
  AuthenticatedAdminModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOutcomesRoute =
  AuthenticatedAdminOutcomesRouteImport.update({
    id: '/outcomes',
    path: '/outcomes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPairingRoute =
  AuthenticatedAdminPairingRouteImport.update({
    id: '/pairing',
    path: '/pairing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPathologyRoute =
  AuthenticatedAdminPathologyRouteImport.update({
    id: '/pathology',
    path: '/pathology',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPerformanceRoute =
  AuthenticatedAdminPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReferenceRoute =
  AuthenticatedAdminReferenceRouteImport.update({
    id: '/reference',
    path: '/reference',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReplayRoute =
  AuthenticatedAdminReplayRouteImport.update({
    id: '/replay',
    path: '/replay',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuppressionRoute =
  AuthenticatedAdminSuppressionRouteImport.update({
    id: '/suppression',
    path: '/suppression',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTrainingRoute =
  AuthenticatedAdminTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTrendsRoute =
  AuthenticatedAdminTrendsRouteImport.update({
    id: '/trends',
    path: '/trends',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminValidateRoute =
  AuthenticatedAdminValidateRouteImport.update({
    id: '/validate',
    path: '/validate',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCaseCaseRefRoute =
  AuthenticatedCaseCaseRefRouteImport.update({
    id: '/case/$caseRef',
    path: '/case/$caseRef',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportIdRoute = AuthenticatedReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminPeopleRoute =
  AuthenticatedAdminAdminPeopleRouteImport.update({
    id: '/admin/people',
    path: '/admin/people',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksCoebisRefitRoute =
  ApiPublicHooksCoebisRefitRouteImport.update({
    id: '/api/public/hooks/coebis-refit',
    path: '/api/public/hooks/coebis-refit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/bedside': typeof AuthenticatedBedsideRoute
  '/cases': typeof AuthenticatedCasesRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/terms': typeof AuthenticatedTermsRoute
  '/bis-benchmark': typeof AuthenticatedAdminBisBenchmarkRoute
  '/blockers': typeof AuthenticatedAdminBlockersRoute
  '/brainwaves': typeof AuthenticatedAdminBrainwavesRoute
  '/calibrate': typeof AuthenticatedAdminCalibrateRoute
  '/capture': typeof AuthenticatedAdminCaptureRoute
  '/coebis': typeof AuthenticatedAdminCoebisRoute
  '/compare': typeof AuthenticatedAdminCompareRoute
  '/corpus-upload': typeof AuthenticatedAdminCorpusUploadRoute
  '/depth': typeof AuthenticatedAdminDepthRoute
  '/depth-intake': typeof AuthenticatedAdminDepthIntakeRoute
  '/discovery': typeof AuthenticatedAdminDiscoveryRoute
  '/drugs': typeof AuthenticatedAdminDrugsRoute
  '/exposure': typeof AuthenticatedAdminExposureRoute
  '/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/flags': typeof AuthenticatedAdminFlagsRoute
  '/ketamine': typeof AuthenticatedAdminKetamineRoute
  '/models': typeof AuthenticatedAdminModelsRoute
  '/outcomes': typeof AuthenticatedAdminOutcomesRoute
  '/pairing': typeof AuthenticatedAdminPairingRoute
  '/pathology': typeof AuthenticatedAdminPathologyRoute
  '/performance': typeof AuthenticatedAdminPerformanceRoute
  '/reference': typeof AuthenticatedAdminReferenceRoute
  '/replay': typeof AuthenticatedAdminReplayRoute
  '/suppression': typeof AuthenticatedAdminSuppressionRoute
  '/training': typeof AuthenticatedAdminTrainingRoute
  '/trends': typeof AuthenticatedAdminTrendsRoute
  '/validate': typeof AuthenticatedAdminValidateRoute
  '/case/$caseRef': typeof AuthenticatedCaseCaseRefRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/admin/people': typeof AuthenticatedAdminAdminPeopleRoute
  '/api/public/hooks/coebis-refit': typeof ApiPublicHooksCoebisRefitRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/bedside': typeof AuthenticatedBedsideRoute
  '/cases': typeof AuthenticatedCasesRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/terms': typeof AuthenticatedTermsRoute
  '/bis-benchmark': typeof AuthenticatedAdminBisBenchmarkRoute
  '/blockers': typeof AuthenticatedAdminBlockersRoute
  '/brainwaves': typeof AuthenticatedAdminBrainwavesRoute
  '/calibrate': typeof AuthenticatedAdminCalibrateRoute
  '/capture': typeof AuthenticatedAdminCaptureRoute
  '/coebis': typeof AuthenticatedAdminCoebisRoute
  '/compare': typeof AuthenticatedAdminCompareRoute
  '/corpus-upload': typeof AuthenticatedAdminCorpusUploadRoute
  '/depth': typeof AuthenticatedAdminDepthRoute
  '/depth-intake': typeof AuthenticatedAdminDepthIntakeRoute
  '/discovery': typeof AuthenticatedAdminDiscoveryRoute
  '/drugs': typeof AuthenticatedAdminDrugsRoute
  '/exposure': typeof AuthenticatedAdminExposureRoute
  '/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/flags': typeof AuthenticatedAdminFlagsRoute
  '/ketamine': typeof AuthenticatedAdminKetamineRoute
  '/models': typeof AuthenticatedAdminModelsRoute
  '/outcomes': typeof AuthenticatedAdminOutcomesRoute
  '/pairing': typeof AuthenticatedAdminPairingRoute
  '/pathology': typeof AuthenticatedAdminPathologyRoute
  '/performance': typeof AuthenticatedAdminPerformanceRoute
  '/reference': typeof AuthenticatedAdminReferenceRoute
  '/replay': typeof AuthenticatedAdminReplayRoute
  '/suppression': typeof AuthenticatedAdminSuppressionRoute
  '/training': typeof AuthenticatedAdminTrainingRoute
  '/trends': typeof AuthenticatedAdminTrendsRoute
  '/validate': typeof AuthenticatedAdminValidateRoute
  '/case/$caseRef': typeof AuthenticatedCaseCaseRefRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/admin/people': typeof AuthenticatedAdminAdminPeopleRoute
  '/api/public/hooks/coebis-refit': typeof ApiPublicHooksCoebisRefitRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/bedside': typeof AuthenticatedBedsideRoute
  '/_authenticated/cases': typeof AuthenticatedCasesRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/terms': typeof AuthenticatedTermsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_admin/bis-benchmark': typeof AuthenticatedAdminBisBenchmarkRoute
  '/_authenticated/_admin/blockers': typeof AuthenticatedAdminBlockersRoute
  '/_authenticated/_admin/brainwaves': typeof AuthenticatedAdminBrainwavesRoute
  '/_authenticated/_admin/calibrate': typeof AuthenticatedAdminCalibrateRoute
  '/_authenticated/_admin/capture': typeof AuthenticatedAdminCaptureRoute
  '/_authenticated/_admin/coebis': typeof AuthenticatedAdminCoebisRoute
  '/_authenticated/_admin/compare': typeof AuthenticatedAdminCompareRoute
  '/_authenticated/_admin/corpus-upload': typeof AuthenticatedAdminCorpusUploadRoute
  '/_authenticated/_admin/depth': typeof AuthenticatedAdminDepthRoute
  '/_authenticated/_admin/depth-intake': typeof AuthenticatedAdminDepthIntakeRoute
  '/_authenticated/_admin/discovery': typeof AuthenticatedAdminDiscoveryRoute
  '/_authenticated/_admin/drugs': typeof AuthenticatedAdminDrugsRoute
  '/_authenticated/_admin/exposure': typeof AuthenticatedAdminExposureRoute
  '/_authenticated/_admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/_authenticated/_admin/flags': typeof AuthenticatedAdminFlagsRoute
  '/_authenticated/_admin/ketamine': typeof AuthenticatedAdminKetamineRoute
  '/_authenticated/_admin/models': typeof AuthenticatedAdminModelsRoute
  '/_authenticated/_admin/outcomes': typeof AuthenticatedAdminOutcomesRoute
  '/_authenticated/_admin/pairing': typeof AuthenticatedAdminPairingRoute
  '/_authenticated/_admin/pathology': typeof AuthenticatedAdminPathologyRoute
  '/_authenticated/_admin/performance': typeof AuthenticatedAdminPerformanceRoute
  '/_authenticated/_admin/reference': typeof AuthenticatedAdminReferenceRoute
  '/_authenticated/_admin/replay': typeof AuthenticatedAdminReplayRoute
  '/_authenticated/_admin/suppression': typeof AuthenticatedAdminSuppressionRoute
  '/_authenticated/_admin/training': typeof AuthenticatedAdminTrainingRoute
  '/_authenticated/_admin/trends': typeof AuthenticatedAdminTrendsRoute
  '/_authenticated/_admin/validate': typeof AuthenticatedAdminValidateRoute
  '/_authenticated/case/$caseRef': typeof AuthenticatedCaseCaseRefRoute
  '/_authenticated/report/$id': typeof AuthenticatedReportIdRoute
  '/_authenticated/_admin/admin/people': typeof AuthenticatedAdminAdminPeopleRoute
  '/api/public/hooks/coebis-refit': typeof ApiPublicHooksCoebisRefitRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bedside'
    | '/cases'
    | '/notes'
    | '/patients'
    | '/sessions'
    | '/settings'
    | '/terms'
    | '/bis-benchmark'
    | '/blockers'
    | '/brainwaves'
    | '/calibrate'
    | '/capture'
    | '/coebis'
    | '/compare'
    | '/corpus-upload'
    | '/depth'
    | '/depth-intake'
    | '/discovery'
    | '/drugs'
    | '/exposure'
    | '/feedback'
    | '/flags'
    | '/ketamine'
    | '/models'
    | '/outcomes'
    | '/pairing'
    | '/pathology'
    | '/performance'
    | '/reference'
    | '/replay'
    | '/suppression'
    | '/training'
    | '/trends'
    | '/validate'
    | '/case/$caseRef'
    | '/report/$id'
    | '/admin/people'
    | '/api/public/hooks/coebis-refit'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/bedside'
    | '/cases'
    | '/notes'
    | '/patients'
    | '/sessions'
    | '/settings'
    | '/terms'
    | '/bis-benchmark'
    | '/blockers'
    | '/brainwaves'
    | '/calibrate'
    | '/capture'
    | '/coebis'
    | '/compare'
    | '/corpus-upload'
    | '/depth'
    | '/depth-intake'
    | '/discovery'
    | '/drugs'
    | '/exposure'
    | '/feedback'
    | '/flags'
    | '/ketamine'
    | '/models'
    | '/outcomes'
    | '/pairing'
    | '/pathology'
    | '/performance'
    | '/reference'
    | '/replay'
    | '/suppression'
    | '/training'
    | '/trends'
    | '/validate'
    | '/case/$caseRef'
    | '/report/$id'
    | '/admin/people'
    | '/api/public/hooks/coebis-refit'
    | '/admin'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_admin'
    | '/_authenticated/bedside'
    | '/_authenticated/cases'
    | '/_authenticated/notes'
    | '/_authenticated/patients'
    | '/_authenticated/sessions'
    | '/_authenticated/settings'
    | '/_authenticated/terms'
    | '/_authenticated/'
    | '/_authenticated/_admin/bis-benchmark'
    | '/_authenticated/_admin/blockers'
    | '/_authenticated/_admin/brainwaves'
    | '/_authenticated/_admin/calibrate'
    | '/_authenticated/_admin/capture'
    | '/_authenticated/_admin/coebis'
    | '/_authenticated/_admin/compare'
    | '/_authenticated/_admin/corpus-upload'
    | '/_authenticated/_admin/depth'
    | '/_authenticated/_admin/depth-intake'
    | '/_authenticated/_admin/discovery'
    | '/_authenticated/_admin/drugs'
    | '/_authenticated/_admin/exposure'
    | '/_authenticated/_admin/feedback'
    | '/_authenticated/_admin/flags'
    | '/_authenticated/_admin/ketamine'
    | '/_authenticated/_admin/models'
    | '/_authenticated/_admin/outcomes'
    | '/_authenticated/_admin/pairing'
    | '/_authenticated/_admin/pathology'
    | '/_authenticated/_admin/performance'
    | '/_authenticated/_admin/reference'
    | '/_authenticated/_admin/replay'
    | '/_authenticated/_admin/suppression'
    | '/_authenticated/_admin/training'
    | '/_authenticated/_admin/trends'
    | '/_authenticated/_admin/validate'
    | '/_authenticated/case/$caseRef'
    | '/_authenticated/report/$id'
    | '/_authenticated/_admin/admin/people'
    | '/api/public/hooks/coebis-refit'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksCoebisRefitRoute: typeof ApiPublicHooksCoebisRefitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bedside': {
      id: '/_authenticated/bedside'
      path: '/bedside'
      fullPath: '/bedside'
      preLoaderRoute: typeof AuthenticatedBedsideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases': {
      id: '/_authenticated/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AuthenticatedCasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terms': {
      id: '/_authenticated/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AuthenticatedTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/bis-benchmark': {
      id: '/_authenticated/_admin/bis-benchmark'
      path: '/bis-benchmark'
      fullPath: '/bis-benchmark'
      preLoaderRoute: typeof AuthenticatedAdminBisBenchmarkRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/blockers': {
      id: '/_authenticated/_admin/blockers'
      path: '/blockers'
      fullPath: '/blockers'
      preLoaderRoute: typeof AuthenticatedAdminBlockersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/brainwaves': {
      id: '/_authenticated/_admin/brainwaves'
      path: '/brainwaves'
      fullPath: '/brainwaves'
      preLoaderRoute: typeof AuthenticatedAdminBrainwavesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/calibrate': {
      id: '/_authenticated/_admin/calibrate'
      path: '/calibrate'
      fullPath: '/calibrate'
      preLoaderRoute: typeof AuthenticatedAdminCalibrateRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/capture': {
      id: '/_authenticated/_admin/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AuthenticatedAdminCaptureRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/coebis': {
      id: '/_authenticated/_admin/coebis'
      path: '/coebis'
      fullPath: '/coebis'
      preLoaderRoute: typeof AuthenticatedAdminCoebisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/compare': {
      id: '/_authenticated/_admin/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedAdminCompareRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/corpus-upload': {
      id: '/_authenticated/_admin/corpus-upload'
      path: '/corpus-upload'
      fullPath: '/corpus-upload'
      preLoaderRoute: typeof AuthenticatedAdminCorpusUploadRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/depth': {
      id: '/_authenticated/_admin/depth'
      path: '/depth'
      fullPath: '/depth'
      preLoaderRoute: typeof AuthenticatedAdminDepthRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/depth-intake': {
      id: '/_authenticated/_admin/depth-intake'
      path: '/depth-intake'
      fullPath: '/depth-intake'
      preLoaderRoute: typeof AuthenticatedAdminDepthIntakeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/discovery': {
      id: '/_authenticated/_admin/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AuthenticatedAdminDiscoveryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/drugs': {
      id: '/_authenticated/_admin/drugs'
      path: '/drugs'
      fullPath: '/drugs'
      preLoaderRoute: typeof AuthenticatedAdminDrugsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/exposure': {
      id: '/_authenticated/_admin/exposure'
      path: '/exposure'
      fullPath: '/exposure'
      preLoaderRoute: typeof AuthenticatedAdminExposureRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/feedback': {
      id: '/_authenticated/_admin/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/flags': {
      id: '/_authenticated/_admin/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof AuthenticatedAdminFlagsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/ketamine': {
      id: '/_authenticated/_admin/ketamine'
      path: '/ketamine'
      fullPath: '/ketamine'
      preLoaderRoute: typeof AuthenticatedAdminKetamineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/models': {
      id: '/_authenticated/_admin/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedAdminModelsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/outcomes': {
      id: '/_authenticated/_admin/outcomes'
      path: '/outcomes'
      fullPath: '/outcomes'
      preLoaderRoute: typeof AuthenticatedAdminOutcomesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/pairing': {
      id: '/_authenticated/_admin/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof AuthenticatedAdminPairingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/pathology': {
      id: '/_authenticated/_admin/pathology'
      path: '/pathology'
      fullPath: '/pathology'
      preLoaderRoute: typeof AuthenticatedAdminPathologyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/performance': {
      id: '/_authenticated/_admin/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedAdminPerformanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/reference': {
      id: '/_authenticated/_admin/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof AuthenticatedAdminReferenceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/replay': {
      id: '/_authenticated/_admin/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof AuthenticatedAdminReplayRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/suppression': {
      id: '/_authenticated/_admin/suppression'
      path: '/suppression'
      fullPath: '/suppression'
      preLoaderRoute: typeof AuthenticatedAdminSuppressionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/training': {
      id: '/_authenticated/_admin/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedAdminTrainingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/trends': {
      id: '/_authenticated/_admin/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedAdminTrendsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/validate': {
      id: '/_authenticated/_admin/validate'
      path: '/validate'
      fullPath: '/validate'
      preLoaderRoute: typeof AuthenticatedAdminValidateRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/case/$caseRef': {
      id: '/_authenticated/case/$caseRef'
      path: '/case/$caseRef'
      fullPath: '/case/$caseRef'
      preLoaderRoute: typeof AuthenticatedCaseCaseRefRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/$id': {
      id: '/_authenticated/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof AuthenticatedReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/people': {
      id: '/_authenticated/_admin/admin/people'
      path: '/admin/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AuthenticatedAdminAdminPeopleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/coebis-refit': {
      id: '/api/public/hooks/coebis-refit'
      path: '/api/public/hooks/coebis-refit'
      fullPath: '/api/public/hooks/coebis-refit'
      preLoaderRoute: typeof ApiPublicHooksCoebisRefitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBisBenchmarkRoute: typeof AuthenticatedAdminBisBenchmarkRoute
  AuthenticatedAdminBlockersRoute: typeof AuthenticatedAdminBlockersRoute
  AuthenticatedAdminBrainwavesRoute: typeof AuthenticatedAdminBrainwavesRoute
  AuthenticatedAdminCalibrateRoute: typeof AuthenticatedAdminCalibrateRoute
  AuthenticatedAdminCaptureRoute: typeof AuthenticatedAdminCaptureRoute
  AuthenticatedAdminCoebisRoute: typeof AuthenticatedAdminCoebisRoute
  AuthenticatedAdminCompareRoute: typeof AuthenticatedAdminCompareRoute
  AuthenticatedAdminCorpusUploadRoute: typeof AuthenticatedAdminCorpusUploadRoute
  AuthenticatedAdminDepthRoute: typeof AuthenticatedAdminDepthRoute
  AuthenticatedAdminDepthIntakeRoute: typeof AuthenticatedAdminDepthIntakeRoute
  AuthenticatedAdminDiscoveryRoute: typeof AuthenticatedAdminDiscoveryRoute
  AuthenticatedAdminDrugsRoute: typeof AuthenticatedAdminDrugsRoute
  AuthenticatedAdminExposureRoute: typeof AuthenticatedAdminExposureRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
  AuthenticatedAdminFlagsRoute: typeof AuthenticatedAdminFlagsRoute
  AuthenticatedAdminKetamineRoute: typeof AuthenticatedAdminKetamineRoute
  AuthenticatedAdminModelsRoute: typeof AuthenticatedAdminModelsRoute
  AuthenticatedAdminOutcomesRoute: typeof AuthenticatedAdminOutcomesRoute
  AuthenticatedAdminPairingRoute: typeof AuthenticatedAdminPairingRoute
  AuthenticatedAdminPathologyRoute: typeof AuthenticatedAdminPathologyRoute
  AuthenticatedAdminPerformanceRoute: typeof AuthenticatedAdminPerformanceRoute
  AuthenticatedAdminReferenceRoute: typeof AuthenticatedAdminReferenceRoute
  AuthenticatedAdminReplayRoute: typeof AuthenticatedAdminReplayRoute
  AuthenticatedAdminSuppressionRoute: typeof AuthenticatedAdminSuppressionRoute
  AuthenticatedAdminTrainingRoute: typeof AuthenticatedAdminTrainingRoute
  AuthenticatedAdminTrendsRoute: typeof AuthenticatedAdminTrendsRoute
  AuthenticatedAdminValidateRoute: typeof AuthenticatedAdminValidateRoute
  AuthenticatedAdminAdminPeopleRoute: typeof AuthenticatedAdminAdminPeopleRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBisBenchmarkRoute: AuthenticatedAdminBisBenchmarkRoute,
  AuthenticatedAdminBlockersRoute: AuthenticatedAdminBlockersRoute,
  AuthenticatedAdminBrainwavesRoute: AuthenticatedAdminBrainwavesRoute,
  AuthenticatedAdminCalibrateRoute: AuthenticatedAdminCalibrateRoute,
  AuthenticatedAdminCaptureRoute: AuthenticatedAdminCaptureRoute,
  AuthenticatedAdminCoebisRoute: AuthenticatedAdminCoebisRoute,
  AuthenticatedAdminCompareRoute: AuthenticatedAdminCompareRoute,
  AuthenticatedAdminCorpusUploadRoute: AuthenticatedAdminCorpusUploadRoute,
  AuthenticatedAdminDepthRoute: AuthenticatedAdminDepthRoute,
  AuthenticatedAdminDepthIntakeRoute: AuthenticatedAdminDepthIntakeRoute,
  AuthenticatedAdminDiscoveryRoute: AuthenticatedAdminDiscoveryRoute,
  AuthenticatedAdminDrugsRoute: AuthenticatedAdminDrugsRoute,
  AuthenticatedAdminExposureRoute: AuthenticatedAdminExposureRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
  AuthenticatedAdminFlagsRoute: AuthenticatedAdminFlagsRoute,
  AuthenticatedAdminKetamineRoute: AuthenticatedAdminKetamineRoute,
  AuthenticatedAdminModelsRoute: AuthenticatedAdminModelsRoute,
  AuthenticatedAdminOutcomesRoute: AuthenticatedAdminOutcomesRoute,
  AuthenticatedAdminPairingRoute: AuthenticatedAdminPairingRoute,
  AuthenticatedAdminPathologyRoute: AuthenticatedAdminPathologyRoute,
  AuthenticatedAdminPerformanceRoute: AuthenticatedAdminPerformanceRoute,
  AuthenticatedAdminReferenceRoute: AuthenticatedAdminReferenceRoute,
  AuthenticatedAdminReplayRoute: AuthenticatedAdminReplayRoute,
  AuthenticatedAdminSuppressionRoute: AuthenticatedAdminSuppressionRoute,
  AuthenticatedAdminTrainingRoute: AuthenticatedAdminTrainingRoute,
  AuthenticatedAdminTrendsRoute: AuthenticatedAdminTrendsRoute,
  AuthenticatedAdminValidateRoute: AuthenticatedAdminValidateRoute,
  AuthenticatedAdminAdminPeopleRoute: AuthenticatedAdminAdminPeopleRoute,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBedsideRoute: typeof AuthenticatedBedsideRoute
  AuthenticatedCasesRoute: typeof AuthenticatedCasesRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTermsRoute: typeof AuthenticatedTermsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCaseCaseRefRoute: typeof AuthenticatedCaseCaseRefRoute
  AuthenticatedReportIdRoute: typeof AuthenticatedReportIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBedsideRoute: AuthenticatedBedsideRoute,
  AuthenticatedCasesRoute: AuthenticatedCasesRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTermsRoute: AuthenticatedTermsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCaseCaseRefRoute: AuthenticatedCaseCaseRefRoute,
  AuthenticatedReportIdRoute: AuthenticatedReportIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksCoebisRefitRoute: ApiPublicHooksCoebisRefitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
